//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaEngine.Editor.Emulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaEngine.Editor.Emulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string EmulatorControl_SetupMenu_Device {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupMenu_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string EmulatorControl_SetupMenu_Orientation {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupMenu_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string EmulatorControl_SetupMenu_Scale {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupMenu_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string EmulatorControl_SetupOrientationMenu_Landscape {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupOrientationMenu_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string EmulatorControl_SetupOrientationMenu_Portrait {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupOrientationMenu_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string EmulatorControl_SetupScaleMenu__100 {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupScaleMenu__100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%.
        /// </summary>
        internal static string EmulatorControl_SetupScaleMenu__50 {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupScaleMenu__50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75%.
        /// </summary>
        internal static string EmulatorControl_SetupScaleMenu__75 {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupScaleMenu__75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering surface.
        /// </summary>
        internal static string EmulatorControl_SetupScreen_Rendering_surface {
            get {
                return ResourceManager.GetString("EmulatorControl_SetupScreen_Rendering_surface", resourceCulture);
            }
        }
    }
}
